-- Updated routes table schema for truck route optimization
DROP TABLE IF EXISTS public.routes;

CREATE TABLE public.routes (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  start_points text NULL,
  end_points text NULL,
  order_number text NULL,
  
  -- Route optimization data
  route_data jsonb NULL,
  vehicle_id text NULL,
  driver_id text NULL,
  
  -- Route metrics
  distance_km numeric NULL,
  duration_minutes integer NULL,
  estimated_eta timestamp with time zone NULL,
  
  -- Truck-specific data
  truck_restrictions jsonb NULL,
  traffic_warnings jsonb NULL,
  route_geometry jsonb NULL,
  tollgates jsonb NULL,
  road_conditions jsonb NULL,
  
  -- Status tracking
  status text DEFAULT 'planned' CHECK (status IN ('planned', 'active', 'completed', 'cancelled')),
  actual_start_time timestamp with time zone NULL,
  actual_end_time timestamp with time zone NULL,
  
  CONSTRAINT routes_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-- Add indexes for better performance
CREATE INDEX idx_routes_order_number ON public.routes(order_number);
CREATE INDEX idx_routes_vehicle_id ON public.routes(vehicle_id);
CREATE INDEX idx_routes_status ON public.routes(status);
CREATE INDEX idx_routes_created_at ON public.routes(created_at);

-- Add comments
COMMENT ON TABLE public.routes IS 'Optimized truck routes with traffic and restriction data';
COMMENT ON COLUMN public.routes.route_data IS 'Complete route optimization data including geometry and waypoints';
COMMENT ON COLUMN public.routes.truck_restrictions IS 'Truck-specific restrictions like bridge heights, weight limits';
COMMENT ON COLUMN public.routes.traffic_warnings IS 'Real-time traffic conditions and warnings';
COMMENT ON COLUMN public.routes.route_geometry IS 'GeoJSON geometry for route visualization';
COMMENT ON COLUMN public.routes.tollgates IS 'Tollgate information including costs and locations';
COMMENT ON COLUMN public.routes.road_conditions IS 'Road conditions, construction, weather alerts';